name: Keep backend awake

on:
  schedule:
    - cron: "*/10 * * * *" # cada 10 minutos
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: curl -f -s "https://pachos-cfo-virtual-backend.onrender.com/health"
